# This file was auto-generated by `agentos init` on Aug 09, 2021 09:12:37.
import agentos
import random


# A random policy to be converted into a wrapper around SB3's PPOPolicy.
class PPOPolicy(agentos.Policy):
    def decide(self, observation, actions):
        return random.choice(actions)

    def improve(self, **kwargs):
        pass

    def observe(self, action, observation, reward, done, info):
        pass
